apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    name: lzs-chatbot-webapp
  name: lzs-chatbot-webapp
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      app: lzs-chatbot-webapp
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lzs-chatbot-webapp
    spec:
      containers:
      - image: syafiqpipe/lzs-chatbot-webapp:1.0.1
        imagePullPolicy: Always   
        name: lzs-chatbot-webapp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30